name: grid_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_map: ^6.1.0
  timeago: ^3.1.0
  geolocator: ^11.1.0
  latlong2: ^0.9.1
  flutter_map_marker_popup: ^6.1.2
  flutter_map_location_marker: ^8.0.8
  flutter_map_marker_cluster: ^1.3.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  matrix: ^0.29.8
  flutter_olm: ^1.4.1
  flutter_openssl_crypto: ^0.3.0
  flutter_secure_storage: ^9.2.2
  flutter_emoji: ^2.5.1
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  crypto: ^3.0.4
  workmanager: ^0.5.2
  encrypt: ^5.0.3
  flutter_map_cancellable_tile_provider: ^2.0.0  # Downgraded to a compatible version
  flutter_launcher_icons: "^0.13.1"
  random_avatar: any # or the latest version on Pub
  url_launcher: ^6.3.0
  http: ^1.2.2
  vector_map_tiles: ^7.3.1
  vector_map_tiles_pmtiles: ^1.3.0
  intl_phone_field: ^3.2.0
  lottie: ^3.1.2
  sleek_circular_slider: ^2.0.1
  flutter_slidable: ^3.1.1
  flutter_dotenv: ^5.1.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcons/appstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/logos/png-file-2.png
    - assets/logos/Brand-Pattern-Low-color.png
    - assets/lottie/lottie-phone-pin.json
    - assets/lottie/lottie-phone-verify.json
    - .env

  fonts:
    - family: GridFont
      fonts:
        - asset: assets/fonts/fontawesome-webfont.ttf
          weight: 700
